### ISSUE TITLE
Failed to resolve reference for provided property: CPL166MTA#cpl166js_api#url

### ISSUE THREAD

**Issue by binhudakhalid** [SAP/cloud-xsa-hybrid-deployment-tutorial#5]
Failed to resolve reference for provided property: a11c68c8-3e6a-46d4-9400-df911eac3b1a-4c2m1u6bq721vccz-CPL166MTA#cpl166js_api#url

with hana 2.0 SPS02

mta.yml

`ID: CPL166MTA
_schema-version: '2.0'
version: 0.0.1
modules:
  - name: cpl166db
    type: hdb
    path: cpl166db
    requires:
      - name: hdi_cpl166db
  - name: cpl166js
    type: nodejs
    path: cpl166js
    provides:
      - name: cpl166js_api
        properties:
          url: '${default-url}'
    requires:
      - name: hdi_cpl166db
      - name: cpl166db
  - name: cpl166ui
    type: html5
    path: cpl166ui
    requires:
      - name: cpl166js_api
        group: destinations
        properties:
          name: cpl166js_be
          url: '~{url}'
resources:
  - name: hdi_cpl166db
    properties:
      hdi-container-name: '${service-name}'
    type: com.sap.xs.hdi-container
`

xs-app.json
`{
  "welcomeFile": "index.html",
  "authenticationMethod": "none",
	"routes": [{
		"source": "^/euro.xsodata/.*$", 
		"destination": "cpl166js_be"
	}, {
         "source": ".*\\.xsjs",
         "destination": "cpl166js_be"
     }]
}`

**Comment by rafal-sap** [comment]
Hi  binhudakhalid,

Could you pelase share some information how did you solced that issue ?

Regards
Rafal
